import random

questions = []

players = [
    ("Rueben Randle",
     "Giants WR who had back-to-back 900+ yard seasons before fading out by 2016."
     ),
    ("Josh Freeman",
     "QB who threw 27 TDs for the Bucs in 2010, then vanished."),
    ("Mike Tolbert",
     "Stocky fullback who was a Pro Bowler with the Panthers."),
    ("Roy Helu", "RB with a breakout rookie season for Washington in 2011."),
    ("Jerome Simpson", "WR best known for a front-flip TD with the Bengals."),
    ("Marcel Reece", "Receiving fullback for the Raiders in the early 2010s."),
    ("Austin Collie",
     "Colts slot WR with Peyton Manning, cut short by concussions."),
    ("Donald Brown",
     "Colts RB drafted in 2009 who had a brief resurgence in 2013."),
    ("Jacquizz Rodgers", "Compact RB with Falcons and Bucs from 2011–2018."),
    ("Austin Pettis", "Rams WR who played alongside Sam Bradford."),
    ("Dexter McCluster", "Gadget player for the Chiefs and Titans."),
    ("Trent Richardson",
     "Browns RB drafted 3rd overall in 2012, traded to the Colts a year later."
     ),
    ("Kevin White",
     "Bears WR drafted in 2015 who barely played due to injuries."),
    ("Justin Blackmon",
     "Elite WR talent from Oklahoma State whose career was derailed by suspensions."
     ), ("Mike Boone", "Vikings RB who was a late-season DFS hero in 2019."),
    ("Benny Snell",
     "Steelers backup RB who started games when Conner was hurt."),
    ("Ty Johnson", "Jets RB who had a random 100-yard game in 2020."),
    ("Salvon Ahmed",
     "Dolphins RB who posted 122 yards and a TD in Week 15 of 2020."),
    ("Richie James",
     "49ers WR who had 184 yards and a TD on Thursday Night Football."),
    ("Dontrelle Inman",
     "Journeyman WR who posted 810 yards for the Chargers in 2016."),
    ("Greg Ward", "Converted QB who led the Eagles in catches in late 2019."),
    ("Zay Jones", "Bills WR who caught 2 TDs in one game and disappeared."),
    ("Logan Thomas", "Former QB turned TE1 for Washington in 2020."),
    ("Foster Moreau",
     "Raiders TE who filled in for Darren Waller with decent production."),
    ("Jesse James",
     "Steelers TE who had a 100-yard game and was never heard from again."),
    ("Case Keenum",
     "Led the Vikings to the NFC title game and was a hot streamer."),
    ("Gardner Minshew",
     "Mullet, mustache, and magic as a Jags rookie streamer."),
    ("Nick Mullens", "49ers QB who had multiple 300-yard games as a fill-in."),
    ("Josh McCown",
     "Streaming staple in the mid-2010s, especially with the Jets."),
    ("Trevor Siemian",
     "Brief starter for the Broncos post-Peyton who flashed in fantasy."),
    ("Bishop Sankey",
     "Titans RB drafted in 2014 who was a trendy fantasy pick, but flopped."),
    ("David Wilson",
     "Giants RB with elite speed, career ended early due to injury."),
    ("Rashaad Penny", "Seahawks 1st-rounder who rarely stayed healthy."),
    ("Kevin White",
     "Top-10 WR pick who barely played due to repeated injuries."),
    ("Laquon Treadwell",
     "1st-round pick who had just 1 catch in his rookie season."),
    ("N'Keal Harry", "Patriots WR taken ahead of DK Metcalf and A.J. Brown."),
    ("J.J. Arcega-Whiteside",
     "Eagles 2nd-round WR who finished with 10 career catches."),
    ("Clive Walford",
     "TE who was expected to break out with the Raiders but never did."),
    ("Maxx Williams",
     "Ravens TE who started in 2015, faded into backup roles."),
    ("Paxton Lynch",
     "Broncos 1st-round QB who couldn't beat out Trevor Siemian."),
    ("Josh Rosen",
     "10th overall pick traded after 1 year, then bounced around."),
    ("DeShone Kizer", "Led the league in INTs as a Browns rookie in 2017."),
    ("Blake Bortles", "Fantasy stat monster turned backup by 2018."),
    ("Jordan Howard",
     "Eagles RB who had 10 rushing TDs in 2019 before vanishing."),
    ("Tim Hightower",
     "Saints RB who came back from 4 years out of the league to become a fantasy playoff hero."
     ),
    ("Benny Cunningham",
     "Rams/Bears RB who had value as a third-down specialist."),
    ("Kenjon Barner",
     "Eagles change-of-pace back and returner who occasionally got goal line looks."
     ),
    ("Damien Williams",
     "Before KC, was a PPR desperation play on the Dolphins."),
    ("Brian Quick",
     "Rams WR who had an inexplicable 3-TD start to the 2014 season."),
    ("Boston Scott", "Short RB who always seemed to score vs. the Giants."),
    ("Demarcus Robinson",
     "Chiefs WR who exploded for 172 yards in Week 2 of 2019."),
    ("Russell Gage", "Late-season Falcons WR who became a solid flex option."),
    ("Jakeem Grant",
     "Return specialist who occasionally filled in as WR3 with a big play."),
    ("Tyler Conklin",
     "Vikings TE who filled in for Irv Smith Jr. and became a fringe TE1."),
    ("Darren Fells", "Texans TE who randomly had 7 TDs in 2019."),
    ("Colt McCoy",
     "Cardinals backup QB who won games and filled in well during injuries."),
    ("Brock Osweiler",
     "Had one huge game for the Dolphins in 2018 and became a brief streamer."
     ),
    ("Matt Barkley",
     "Bills backup QB who threw 2 TDs in a surprise start vs. the Jets."),
    ("Ronald Jones",
     "Bucs 2nd-round RB who took years to develop and lost snaps to Fournette."
     ),
    ("Corey Coleman",
     "2016 1st-round WR who struggled with injuries and drops."),
    ("Denzel Mims",
     "2020 2nd-round pick for the Jets who couldn’t crack the depth chart."),
    ("Chris Herndon",
     "Jets TE who broke out as a rookie then completely disappeared."),
    ("Austin Seferian-Jenkins",
     "Talented TE who never reached expectations with the Bucs and Jets."),
    ("Isaiah Wilson",
     "Titans 1st-round OT in 2020 who played just 1 NFL snap."),
    ("Paul Richardson",
     "Seahawks WR who had some explosive playoff moments and sleeper appeal in 2017."
     ),
    ("Hakeem Butler",
     "Converted to TE but never caught an NFL pass despite hype in 2019."),
    ("Montee Ball",
     "Wisconsin legend drafted by the Broncos, out of the league in 2 years."),
    ("Eddie Lacy",
     "Started strong with the Packers, but conditioning issues ended his career early."
     ),
    ("Charcandrick West",
     "Chiefs RB who started over Knile Davis and filled in for Jamaal Charles in 2015."
     ),
    ("Marquise Goodwin",
     "Olympic-speed WR who had 962 yards for the 49ers in 2017."),
    ("Chris Conley",
     "Chiefs WR known for testing numbers, scored 5 TDs in 2018."),
    ("Tavarres King",
     "Giants WR who filled in after Odell and Shepard got injured."),
    ("Chris Hogan",
     "Patriots WR who averaged 17.9 yards per catch in 2016 and had playoff relevance."
     ),
    ("Will Tye",
     "Giants TE who caught 90 balls between 2015 and 2016 and was briefly a TE1 streamer."
     ),
    ("Dwayne Allen",
     "Colts TE who had 8 TDs in 2014 and then faded into TE2 purgatory."),
    ("Cameron Artis-Payne",
     "Panthers backup who was the hot CMC handcuff before it was cool."),
    ("Khiry Robinson",
     "Saints RB who looked like the Ingram heir but was derailed by injuries."
     ),
    ("Ka’Deem Carey",
     "Bears RB who was supposed to take over after Matt Forte."),
    ("Rishard Matthews",
     "Titans WR who had 945 yards and 9 TDs in 2016 out of nowhere."),
    ("Thaddeus Lewis",
     "Bills QB who randomly started 5 games in 2013 and threw 4 TDs."),
    ("Matt McGloin",
     "Undrafted Raiders QB who filled in for Terrelle Pryor and threw for 3 TDs in his first start."
     ),
    ("T.J. Yates",
     "Texans backup QB who led a playoff win in 2011 and had a few fantasy fill-in starts."
     ),
    ("Scott Tolzien",
     "Packers and Colts backup who had to start after injuries — INTs were guaranteed."
     ),
    ("Charlie Whitehurst",
     "Clipboard Jesus started games for the Titans in 2014 and threw 7 TDs."),
    ("Case Keenum",
     "Before the Vikings run, he had random streaming success with the Rams and Texans."
     ),
    ("Brian Hoyer",
     "Streamer favorite in Cleveland, Houston, Chicago… everywhere."),
    ("Ryan Fitzpatrick",
     "Journeyman who delivered multi-TD games with the Jets, Bucs, Dolphins."),
    ("Mike Glennon",
     "Started games for the Bucs, Bears, Jags, Giants... and had deep league value briefly."
     ),
    ("Matt Cassel",
     "Never lived up to his 2008 Pats season but streamed well in KC and Dallas."
     ),
    ("Mark Sanchez",
     "Jets QB who had one magical playoff run and one magical 4-TD game."),
    ("Colt McCoy",
     "Played sparingly across 3+ teams but always gave 225 yards and 1 TD in relief."
     ),
    ("Brandon Weeden",
     "Browns QB who started 15 games as a rookie, then bounced around Dallas and Houston."
     ),
    ("Kellen Clemens",
     "Longtime backup who had spot starts for the Rams and Chargers."),
    ("Luke McCown",
     "Made late-season spot starts for the Saints and Jags in the early/mid-2010s."
     ),
    ("E.J. Manuel",
     "Bills 1st-rounder who never panned out but had some garbage-time fantasy value."
     ),
    ("Trevor Siemian",
     "Started 14 games for the Broncos post-Peyton and had a few 300-yard games."
     ),
    ("C.J. Beathard",
     "49ers backup who had usable fantasy weeks when Garoppolo was out."),
    ("Matt Moore",
     "Dolphins backup who had a few multi-TD games whenever Tannehill got hurt."
     ),
    ("Robert Turbin",
     "Marshawn Lynch’s backup in Seattle, stole some red zone carries."),
    ("Cecil Shorts",
     "Jags WR who had five 100-yard games in 2012 with Blaine Gabbert throwing to him."
     ),
    ("Chris Polk", "Eagles and Texans RB who vultured TDs in 2014 and 2015."),
    ("Andre Holmes",
     "Raiders WR who was a red-zone-only play with 4–5 TD seasons."),
    ("Dion Sims",
     "Dolphins TE who was a streamer based on matchup, not talent."),
    ("Vick Ballard",
     "Colts RB who rushed for 814 yards as a rookie in 2012, then tore his ACL."
     ),
    ("Jordan Todman",
     "Jags RB who replaced MJD and had a 100-yard game in 2013."),
    ("DeAngelo Williams",
     "Old Steelers backup who was an elite starter when Le’Veon Bell was suspended."
     ),
    ("Albert Wilson",
     "Chiefs WR who exploded for 147 yards and 2 TDs in a single game with Miami."
     ),
    ("Austin Ekeler",
     "Before he was elite, he was Melvin Gordon’s handcuff and a flex flyer."),
    ("Jeremy Kerley", "Jets slot WR who led the team in targets in 2012."),
    ("Jarius Wright",
     "Vikings WR who was the 3rd option behind Diggs and Thielen, but always seemed to score."
     )
]

names = [name for name, _ in players]

# Generate 300 randomized "guess who" questions
for i, (answer, clue) in enumerate(players):  # 60 players * 5 = 300 questions
    wrong_choices = random.sample([n for n in names if n != answer], 3)
    choices = wrong_choices + [answer]
    random.shuffle(choices)
    questions.append({"question": clue, "choices": choices, "answer": answer})
